### PR TITLE
try to add coverage

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by tertsdiepraam** [comment]
I think we don't need all platforms for this library, because there's no platform-specific code. Though adding them doesn't hurt I suppose.

**Comment by sylvestre** [comment]
it is still good to have CI on different platforms :)

**Comment by tertsdiepraam** [comment]
Fair enough! This looks good to me. Is it working as intended?

**Comment by sylvestre** [comment]
yeah, ship it :)

**Pull request merged**
